name: AI Japanese Translator
on:
  push:
    paths:
      - 'data/materi.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install google-generativeai

      - name: Run Translation Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python translator.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/trans.json
          git commit -m "Update Terjemahan Kanji Otomatis [skip ci]" || exit 0
          git push
